import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { RandomlistComponent } from "../randomlist/randomlist.component";
import { Title, Meta } from '@angular/platform-browser';

@Component({
  selector: 'app-soundatte',
  standalone: true,
  imports: [CommonModule, RandomlistComponent],
  templateUrl: './soundatte.component.html',
  styleUrl: './soundatte.component.css'
})
export class SoundatteComponent implements OnInit {

  constructor(private title: Title, private meta: Meta) {}

  ngOnInit(): void {
    // ✅ SEO Title
    this.title.setTitle('Sound Attenuators UAE | Noise Control HVAC Systems | MEPTECH');

    // ✅ Meta Description
    this.meta.updateTag({
      name: 'description',
      content:
        'Reduce HVAC noise with sound attenuators in UAE. Ensure quiet operation, improved comfort, and efficient airflow for commercial and industrial spaces.',
    });

    // ✅ Keywords
    this.meta.updateTag({
      name: 'keywords',
      content:
        'sound attenuators UAE, HVAC noise control UAE, duct silencers UAE, acoustic attenuators Dubai, HVAC sound insulation UAE',
    });

    // ✅ Open Graph
    this.meta.updateTag({
      property: 'og:title',
      content: 'Sound Attenuators UAE | Noise Control HVAC Systems | MEPTECH',
    });

    this.meta.updateTag({
      property: 'og:description',
      content:
        'Reduce HVAC noise with sound attenuators in UAE. Ensure quiet operation, improved comfort, and efficient airflow for commercial and industrial spaces.',
    });
  }

  product = {
    mainImg: '/products/soundatte/main.jpg',
    name: 'Sound Attenuators',
    short: `Sound attenuators are essential components in HVAC systems used to reduce noise generated by airflow and mechanical equipment. They are typically installed within duct systems to ensure quieter operation and improved acoustic comfort.

These units consist of specially designed baffles lined with sound-absorbing insulation materials. By optimizing baffle configuration and dimensions, sound attenuators can effectively reduce a wide range of frequencies, including low, mid, and high-frequency noise.

Unlike standard lined ductwork, sound attenuators provide superior noise reduction across a broader frequency spectrum. Some designs also function as Helmholtz resonators, acting as passive noise control systems for enhanced performance in commercial and industrial HVAC applications.`
  };

}